version: '3.7'
services: 
  details:
    build: ./details
    ports:
      - "8080:8080"
  reviews:
    build: ./reviews
    ports:
      - "9080:9080"
    environment:
      RATINGS_SERVICE: http://ratings:8081
      ENABLE_RATINGS: "true"
      STAR_COLOR: blue
  ratings:
    build: ./ratings
    ports:
      - "8081:8081"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: rating
      MONGO_DB_PASSWORD: password
  mongodb:
    image: bitnami/mongodb:4.4.4-debian-10-r5
    volumes:
      - "./ratings/databases:/docker-entrypoint-initdb.d"
    environment: 
        MONGODB_ROOT_PASSWORD: PASSWORD
        MONDODB_USERNAME: rating
        MONDODB_PASSWORD: password
        MONGODB_DATABASE: ratings
  productpage:
    build: ./productpage
    ports:
      - "8082:8082"
